apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key-id
            name: aws-secrets-manager-credentials
            namespace: external-secrets-operator
          secretAccessKeySecretRef:
            key: secret-access-key
            name: aws-secrets-manager-credentials
            namespace: external-secrets-operator
      
