apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-external-secret
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: test
  data:
    - secretKey: test
      remoteRef:
        key: intexarep/test
        property: test