apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-workloads
  namespace: gitops-platform
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/exarep/gitops-platform.git
    targetRevision: main
    path: clusters/hub/preproduction/gitops-workloads
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
