apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: gitops-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/exarep/gitops-platform.git
    targetRevision: main
    path: clusters/hub/preproduction/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
